#!/usr/bin/env python3
"""Regenerate guard-fixtures.ts from config/guard-rules.json and config/guard-corpus.json.

The `claude plugin test` environment has no file system, so the TypeScript tests embed the
rules table and the parity corpus as data. Run with --check to fail when the embedded copy
has drifted from the config files. Python 3.11+ stdlib only."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent / 'guard-fixtures.ts'


def render():
    rules = (ROOT / 'config/guard-rules.json').read_text(encoding='utf-8')
    corpus = json.loads((ROOT / 'config/guard-corpus.json').read_text(encoding='utf-8'))
    return ('// Generated by hooks/mod/fixtures/sync.py from config/guard-rules.json and config/guard-corpus.json.\n'
            '// Do not edit by hand; run `python3 plugins/orchestra/hooks/mod/fixtures/sync.py`.\n\n'
            'export const RULES_JSON: string = ' + json.dumps(rules) + ';\n\n'
            'export type CorpusCase = { id: string; input: unknown; class: string; category?: string; decision_category?: string };\n\n'
            'export const CORPUS: CorpusCase[] = ' + json.dumps(corpus['cases'], indent=1, ensure_ascii=True) + ';\n')


def main(argv):
    text = render()
    if '--check' in argv:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
            print('guard-fixtures.ts is stale: run hooks/mod/fixtures/sync.py', file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
